# Generated by Django 2.2.7 on 2021-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('filling', models.TextField(verbose_name='Ингредиенты')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('type', models.CharField(choices=[('P', 'Пицца'), ('D', 'Напитки'), ('S', 'Снеки')], default='P', max_length=1, verbose_name='Тип')),
            ],
        ),
    ]
